### ISSUE TITLE
Invalid Page URL error with functioning link

### ISSUE THREAD

**Issue by alexcarcoana** [asnunes/notion-page-to-html-api#2]
When I upload a public link such as this one:
https://picayune-slice-2e6.notion.site/Alex-DC-s-Design-Portfolio-c57f657f2ff043b88d43ae227f45a16f

I get the following error
`InvalidPageUrlError: Url "https://picayune-slice-2e6.notion.site/Alex-DC-s-Design-Portfolio-c57f657f2ff043b88d43ae227f45a16f" is not a valid notion page.`

I don't know why my Notion URL looks like that but it does and I am not sure if there is any way to make a URL like that work without editing the URL before pasting it in.

**Comment by heywobu** [comment]
Are you sure this link is public? My API call ended up looking like this: https://notion-page-to-html-api.vercel.app/html?id=12e57022824b46f7ac776fad0be3ec69
